# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtGui import QIcon
import sys


class Ui_Dialog(QtWidgets.QMainWindow):
    def setupUi(self, Dialog, window_title, text, font_size):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setWindowTitle(window_title)
        Dialog.setWindowIcon(QIcon("D:/all/all packs/Code/Python/2023/Для коледжа/Pinloader/New realization/UI/logo.png"))
        Dialog.setStyleSheet("background-color: rgb(30,30,30);")

        self.OkeyButton = QtWidgets.QPushButton(Dialog) #Кнопка "хорошо", которая закрывает окно
        self.OkeyButton.setGeometry(QtCore.QRect(100, 240, 200, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.OkeyButton.setFont(font)
        self.OkeyButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.OkeyButton.setAutoFillBackground(False)
        self.OkeyButton.setStyleSheet("background-color: rgb(136,68,236);\n"
"color: rgb(255, 255, 255);")
        self.OkeyButton.setDefault(False)
        self.OkeyButton.setFlat(False)
        self.OkeyButton.setObjectName("OkeyButton")
        self.OkeyButton.clicked.connect(lambda: self.close_function(Dialog))

        self.logo = QtWidgets.QLabel(Dialog) #логотип
        self.logo.setGeometry(QtCore.QRect(25, 30, 130, 130))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("D:/all/all packs/Code/Python/2023/Для коледжа/Pinloader/New realization/UI/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")

        self.name = QtWidgets.QLabel(Dialog) #название программы под лого
        self.name.setGeometry(QtCore.QRect(25, 160, 130, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.name.setFont(font)
        self.name.setStyleSheet("color: rgb(255, 255, 255);")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")

        self.main_text = QtWidgets.QLabel(Dialog) #основной текст ошибки или уведомления
        self.main_text.setGeometry(QtCore.QRect(180, 40, 221, 161))
        font = QtGui.QFont()
        font.setPointSize(font_size)
        font.setBold(True)
        font.setWeight(75)
        self.main_text.setFont(font)
        self.main_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.main_text.setObjectName("main_text")



        self.retranslateUi(text)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, text):
        _translate = QtCore.QCoreApplication.translate
        self.OkeyButton.setText(_translate("Dialog", "Хорошо"))
        self.name.setText(_translate("Dialog", "Pinloader"))
        self.main_text.setText(_translate("Dialog", text))

    def close_function(self, Dialog): #закрывает окно по нажатию кнопки "хорошо"
        Dialog.close()

